// prisma/seed-data/teams.ts
export type TeamSeed = {
  name: string;
  arena: string;
  arenaCapacity: number;
  city: string;
  manager: string;
  premierleagueTitles: number;
  faCupTitles: number;
  marathonTablePlacement: number;
  marathonTablePoints: number;
  recordGoalscorer: string;
  recordGoals: number;
  homeshirtsColor: string;
  awayshirtsColor: string;
  clubStarted: string; // YYYY-MM-DD
  lastPromotionYear: number | null; // År när laget senast blev uppflyttat (null = aldrig nedflyttat)
  lastPromotionSeason: string | null; // Säsong när laget senast blev uppflyttat (ex: "25/26")
  isFoundingMember: boolean; // True = varit med från Premier League start 1992
};

export const teams: TeamSeed[] = [
  {
    name: "Arsenal",
    arena: "Emirates Stadium",
    arenaCapacity: 60704,
    city: "London",
    manager: "Mikel Arteta",
    premierleagueTitles: 3,
    faCupTitles: 14,
    marathonTablePlacement: 2,
    marathonTablePoints: 2398,
    recordGoalscorer: "Thierry Henry",
    recordGoals: 228,
    homeshirtsColor: "Red",
    awayshirtsColor: "White",
    clubStarted: "1886-01-01",
    lastPromotionYear: null,
    lastPromotionSeason: null,
    isFoundingMember: true
  },
  {
    name: "Aston Villa",
    arena: "Villa Park",
    arenaCapacity: 42657,
    city: "Birmingham",
    manager: "Unai Emery",
    premierleagueTitles: 0,
    faCupTitles: 7,
    marathonTablePlacement: 9,
    marathonTablePoints: 1556,
    recordGoalscorer: "Billy Walker",
    recordGoals: 244,
    homeshirtsColor: "Claret & Blue",
    awayshirtsColor: "White",
    clubStarted: "1874-01-01",
    lastPromotionYear: null,
    lastPromotionSeason: null,
    isFoundingMember: true
  },
  {
    name: "AFC Bournemouth",
    arena: "Vitality Stadium",
    arenaCapacity: 11364,
    city: "Bournemouth",
    manager: "Andoni Iraola",
    premierleagueTitles: 0,
    faCupTitles: 0,
    marathonTablePlacement: 29,
    marathonTablePoints: 364,
    recordGoalscorer: "Ted MacDougall",
    recordGoals: 197,
    homeshirtsColor: "Red & Black",
    awayshirtsColor: "White",
    clubStarted: "1899-01-01",
    lastPromotionYear: 2022,
    lastPromotionSeason: "22/23",
    isFoundingMember: false
  },
  {
    name: "Brentford",
    arena: "Gtech Community Stadium",
    arenaCapacity: 17250,
    city: "London",
    manager: "Keith Andrews",
    premierleagueTitles: 0,
    faCupTitles: 0,
    marathonTablePlacement: 41,
    marathonTablePoints: 204,
    recordGoalscorer: "Jim Towers",
    recordGoals: 163,
    homeshirtsColor: "Red & White",
    awayshirtsColor: "Black",
    clubStarted: "1889-01-01",
    lastPromotionYear: 2021,
    lastPromotionSeason: "21/22",
    isFoundingMember: false
  },
  {
    name: "Brighton & Hove Albion",
    arena: "Amex Stadium",
    arenaCapacity: 31800,
    city: "Brighton",
    manager: "Fabian Hürzeler",
    premierleagueTitles: 0,
    faCupTitles: 0,
    marathonTablePlacement: 26,
    marathonTablePoints: 385,
    recordGoalscorer: "Tommy Cook",
    recordGoals: 123,
    homeshirtsColor: "Blue & White",
    awayshirtsColor: "Yellow",
    clubStarted: "1901-01-01",
    lastPromotionYear: 2017,
    lastPromotionSeason: "17/18",
    isFoundingMember: false
  },
  {
    name: "Burnley",
    arena: "Turf Moor",
    arenaCapacity: 21944,
    city: "Burnley",
    manager: "Scott Parker",
    premierleagueTitles: 0,
    faCupTitles: 1,
    marathonTablePlacement: 31,
    marathonTablePoints: 353,
    recordGoalscorer: "George Beel",
    recordGoals: 188,
    homeshirtsColor: "Claret & Blue",
    awayshirtsColor: "White",
    clubStarted: "1882-01-01",
    lastPromotionYear: 2025,
    lastPromotionSeason: "25/26",
    isFoundingMember: false
  },
  {
    name: "Chelsea",
    arena: "Stamford Bridge",
    arenaCapacity: 40343,
    city: "London",
    manager: "Enzo Maresca",
    premierleagueTitles: 5,
    faCupTitles: 8,
    marathonTablePlacement: 4,
    marathonTablePoints: 2322,
    recordGoalscorer: "Frank Lampard",
    recordGoals: 211,
    homeshirtsColor: "Blue",
    awayshirtsColor: "White",
    clubStarted: "1905-03-10",
    lastPromotionYear: null,
    lastPromotionSeason: null,
    isFoundingMember: true
  },
  {
    name: "Crystal Palace",
    arena: "Selhurst Park",
    arenaCapacity: 25486,
    city: "London",
    manager: "Oliver Glasner",
    premierleagueTitles: 0,
    faCupTitles: 0,
    marathonTablePlacement: 16,
    marathonTablePoints: 720,
    recordGoalscorer: "Peter Simpson",
    recordGoals: 165,
    homeshirtsColor: "Red & Blue",
    awayshirtsColor: "White",
    clubStarted: "1905-01-01",
    lastPromotionYear: 2013,
    lastPromotionSeason: "13/14",
    isFoundingMember: false
  },
  {
    name: "Everton",
    arena: "Goodison Park",
    arenaCapacity: 39414,
    city: "Liverpool",
    manager: "David Moyes",
    premierleagueTitles: 0,
    faCupTitles: 5,
    marathonTablePlacement: 7,
    marathonTablePoints: 1705,
    recordGoalscorer: "Dixie Dean",
    recordGoals: 383,
    homeshirtsColor: "Blue",
    awayshirtsColor: "White",
    clubStarted: "1878-01-01",
    lastPromotionYear: null,
    lastPromotionSeason: null,
    isFoundingMember: true
  },
  {
    name: "Fulham",
    arena: "Craven Cottage",
    arenaCapacity: 25700,
    city: "London",
    manager: "Marco Silva",
    premierleagueTitles: 0,
    faCupTitles: 0,
    marathonTablePlacement: 15,
    marathonTablePoints: 801,
    recordGoalscorer: "Gordon Davies",
    recordGoals: 178,
    homeshirtsColor: "White",
    awayshirtsColor: "Black",
    clubStarted: "1879-01-01",
    lastPromotionYear: 2022,
    lastPromotionSeason: "22/23",
    isFoundingMember: false
  },
  {
    name: "Leeds United",
    arena: "Elland Road",
    arenaCapacity: 37892,
    city: "Leeds",
    manager: "Daniel Farke",
    premierleagueTitles: 0,
    faCupTitles: 1,
    marathonTablePlacement: 14,
    marathonTablePoints: 827,
    recordGoalscorer: "Peter Lorimer",
    recordGoals: 238,
    homeshirtsColor: "White",
    awayshirtsColor: "Yellow",
    clubStarted: "1919-10-17",
    lastPromotionYear: 2025,
    lastPromotionSeason: "25/26",
    isFoundingMember: false
  },
  {
    name: "Liverpool",
    arena: "Anfield",
    arenaCapacity: 61276,
    city: "Liverpool",
    manager: "Arne Slot",
    premierleagueTitles: 2,
    faCupTitles: 8,
    marathonTablePlacement: 3,
    marathonTablePoints: 2357,
    recordGoalscorer: "Ian Rush",
    recordGoals: 346,
    homeshirtsColor: "Red",
    awayshirtsColor: "White",
    clubStarted: "1892-06-03",
    lastPromotionYear: null,
    lastPromotionSeason: null,
    isFoundingMember: true
  },
  {
    name: "Manchester City",
    arena: "Etihad Stadium",
    arenaCapacity: 53400,
    city: "Manchester",
    manager: "Pep Guardiola",
    premierleagueTitles: 8,
    faCupTitles: 7,
    marathonTablePlacement: 6,
    marathonTablePoints: 1887,
    recordGoalscorer: "Sergio Agüero",
    recordGoals: 260,
    homeshirtsColor: "Sky Blue",
    awayshirtsColor: "White",
    clubStarted: "1880-01-01",
    lastPromotionYear: 2002,
    lastPromotionSeason: "02/03",
    isFoundingMember: false
  },
  {
    name: "Manchester United",
    arena: "Old Trafford",
    arenaCapacity: 74310,
    city: "Manchester",
    manager: "Rúben Amorim",
    premierleagueTitles: 13,
    faCupTitles: 13,
    marathonTablePlacement: 1,
    marathonTablePoints: 2550,
    recordGoalscorer: "Wayne Rooney",
    recordGoals: 253,
    homeshirtsColor: "Red",
    awayshirtsColor: "White",
    clubStarted: "1878-01-01",
    lastPromotionYear: null,
    lastPromotionSeason: null,
    isFoundingMember: true
  },
  {
    name: "Newcastle United",
    arena: "St James' Park",
    arenaCapacity: 52305,
    city: "Newcastle upon Tyne",
    manager: "Eddie Howe",
    premierleagueTitles: 0,
    faCupTitles: 6,
    marathonTablePlacement: 8,
    marathonTablePoints: 1613,
    recordGoalscorer: "Alan Shearer",
    recordGoals: 206,
    homeshirtsColor: "Black & White",
    awayshirtsColor: "Blue",
    clubStarted: "1892-12-09",
    lastPromotionYear: 2017,
    lastPromotionSeason: "17/18",
    isFoundingMember: false
  },
  {
    name: "Nottingham Forest",
    arena: "City Ground",
    arenaCapacity: 30445,
    city: "Nottingham",
    manager: "Nuno Espírito Santo",
    premierleagueTitles: 0,
    faCupTitles: 2,
    marathonTablePlacement: 27,
    marathonTablePoints: 379,
    recordGoalscorer: "Grenville Morris",
    recordGoals: 217,
    homeshirtsColor: "Red",
    awayshirtsColor: "White",
    clubStarted: "1865-01-01",
    lastPromotionYear: 2022,
    lastPromotionSeason: "22/23",
    isFoundingMember: false
  },
  {
    name: "Sunderland",
    arena: "Stadium of Light",
    arenaCapacity: 49000,
    city: "Sunderland",
    manager: "Régis Le Bris",
    premierleagueTitles: 0,
    faCupTitles: 2,
    marathonTablePlacement: 18,
    marathonTablePoints: 626,
    recordGoalscorer: "Bobby Gurney",
    recordGoals: 228,
    homeshirtsColor: "Red & White",
    awayshirtsColor: "Black",
    clubStarted: "1879-01-01",
    lastPromotionYear: 2025,
    lastPromotionSeason: "25/26",
    isFoundingMember: false
  },
  {
    name: "Tottenham Hotspur",
    arena: "Tottenham Hotspur Stadium",
    arenaCapacity: 62850,
    city: "London",
    manager: "Thomas Frank",
    premierleagueTitles: 0,
    faCupTitles: 8,
    marathonTablePlacement: 5,
    marathonTablePoints: 1961,
    recordGoalscorer: "Harry Kane",
    recordGoals: 280,
    homeshirtsColor: "White",
    awayshirtsColor: "Navy",
    clubStarted: "1882-01-01",
    lastPromotionYear: null,
    lastPromotionSeason: null,
    isFoundingMember: true
  },
  {
    name: "West Ham United",
    arena: "London Stadium",
    arenaCapacity: 62500,
    city: "London",
    manager: "Graham Potter",
    premierleagueTitles: 0,
    faCupTitles: 3,
    marathonTablePlacement: 10,
    marathonTablePoints: 1396,
    recordGoalscorer: "Vic Watson",
    recordGoals: 326,
    homeshirtsColor: "Claret & Blue",
    awayshirtsColor: "White",
    clubStarted: "1895-01-01",
    lastPromotionYear: 2012,
    lastPromotionSeason: "12/13",
    isFoundingMember: false
  },
  {
    name: "Wolverhampton Wanderers",
    arena: "Molineux Stadium",
    arenaCapacity: 32050,
    city: "Wolverhampton",
    manager: "Vítor Pereira",
    premierleagueTitles: 0,
    faCupTitles: 4,
    marathonTablePlacement: 21,
    marathonTablePoints: 477,
    recordGoalscorer: "Steve Bull",
    recordGoals: 306,
    homeshirtsColor: "Gold",
    awayshirtsColor: "Black",
    clubStarted: "1877-01-01",
    lastPromotionYear: 2018,
    lastPromotionSeason: "18/19",
    isFoundingMember: false
  }
];
